/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UploadPropertyIdRouteImport } from './routes/upload/$propertyId'
import { Route as UploadVerifyImportIdRouteImport } from './routes/upload/verify/$importId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadPropertyIdRoute = UploadPropertyIdRouteImport.update({
  id: '/upload/$propertyId',
  path: '/upload/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadVerifyImportIdRoute = UploadVerifyImportIdRouteImport.update({
  id: '/upload/verify/$importId',
  path: '/upload/verify/$importId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/upload/$propertyId': typeof UploadPropertyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/upload/verify/$importId': typeof UploadVerifyImportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/upload/$propertyId': typeof UploadPropertyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/upload/verify/$importId': typeof UploadVerifyImportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/upload/$propertyId': typeof UploadPropertyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/upload/verify/$importId': typeof UploadVerifyImportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/upload/$propertyId'
    | '/api/auth/$'
    | '/upload/verify/$importId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/upload/$propertyId'
    | '/api/auth/$'
    | '/upload/verify/$importId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/upload/$propertyId'
    | '/api/auth/$'
    | '/upload/verify/$importId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  OnboardingRoute: typeof OnboardingRoute
  UploadPropertyIdRoute: typeof UploadPropertyIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  UploadVerifyImportIdRoute: typeof UploadVerifyImportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/$propertyId': {
      id: '/upload/$propertyId'
      path: '/upload/$propertyId'
      fullPath: '/upload/$propertyId'
      preLoaderRoute: typeof UploadPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/verify/$importId': {
      id: '/upload/verify/$importId'
      path: '/upload/verify/$importId'
      fullPath: '/upload/verify/$importId'
      preLoaderRoute: typeof UploadVerifyImportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  OnboardingRoute: OnboardingRoute,
  UploadPropertyIdRoute: UploadPropertyIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  UploadVerifyImportIdRoute: UploadVerifyImportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
